### ISSUE TITLE
Prototype pollution method in js-prim (introduced through http-signature)

### ISSUE THREAD

**Issue by JJ** [cypress-io/request#10]
### Summary

[This vulnerability](https://snyk.io/test/npm/request) revealed by snyk

### Possible Solution

Keep an eye on [this PR](https://github.com/joyent/node-http-signature/pull/125) which fixes the dependency and upgrade accordingly.

**Comment by wrslatz** [comment]
https://github.com/joyent/node-http-signature/pull/125 was merged and released in `http-signature@1.3.6` just now

**Comment by flotwig** [comment]
Closed in #11
