### ISSUE TITLE
Server-Side Request Forgery in Request

### ISSUE THREAD

**Issue by vadimka123** [cypress-io/request#34]
The `request` package through 2.88.2 for Node.js and the `@cypress/request` package through 2.88.11 allow a bypass of SSRF mitigations via an attacker-controller server that does a cross-protocol redirect (HTTP to HTTPS, or HTTPS to HTTP).

NOTE: The `request` package is no longer supported by the maintainer.

**Comment by LubosK** [comment]
bump

**Comment by ewoelfel** [comment]
duplicate of #27 pr fixing it can be found under https://github.com/cypress-io/request/pull/28
